theme: jekyll-theme-minimal
logo: /images/brown_trout.jpg
title: Grady B. Wright
description: Professor<br>
[Department of Mathematics](https://math.boisestate.edu)<br>
[Boise State University](https://www.boisestate.edu)<br>
Boise, Idaho<br>
`gradywright@boisestate.edu`<br>
