theme: jekyll-theme-minimal
logo: /images/brown_trout.jpg
title: Grady B. Wright
description: Professor<br> <a href="https://math.boisestate.edu">Department of Mathematics</a><br> <a href="https://www.boisestate.edu">Boise State University</a><br> Boise, Idaho, USA<br>gradywright@boisestate.edu <br><a href="publications.html"><button style="color:blue;text-align:center">Publications</button></a>
